
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;

namespace DataTable
{
    public class DataTableList
    {
        public Game.TbSkillConfig TbSkillConfig {get; }
        public Game.TbBuffConfig TbBuffConfig {get; }
        public Game.TbActionConfig TbActionConfig {get; }

        public System.Collections.Generic.Dictionary<System.Type, IDataTable> DataTableDict { get; }

        public DataTableList(System.Func<string, JArray> loader)
        {
            TbSkillConfig = new Game.TbSkillConfig(loader("game_tbskillconfig"));
            TbBuffConfig = new Game.TbBuffConfig(loader("game_tbbuffconfig"));
            TbActionConfig = new Game.TbActionConfig(loader("game_tbactionconfig"));

            DataTableDict = new System.Collections.Generic.Dictionary<System.Type, IDataTable>()
            {
                { typeof(Game.TbSkillConfig), TbSkillConfig },
                { typeof(Game.TbBuffConfig), TbBuffConfig },
                { typeof(Game.TbActionConfig), TbActionConfig },
            };

            ResolveRef();
        }
        
        private void ResolveRef()
        {
            TbSkillConfig.ResolveRef(this);
            TbBuffConfig.ResolveRef(this);
            TbActionConfig.ResolveRef(this);
        }
    }

}

