//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameMain.UI
{
    /// <summary>
    /// 界面Id。
    /// </summary>
    public enum UIFormId
    {
        LoginAccountForm = 1,
        LoginForm = 2,
    }
}
