//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using HoweFramework;

namespace GameMain.UI
{
    /// <summary>
    /// 界面绑定。
    /// </summary>
    public static class UIFormBindings
    {
        public static readonly FairyGUIFormBinding[] Bindings = new FairyGUIFormBinding[]
        {
        };
    }
}
