//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using HoweFramework;

namespace GameMain.UI
{
    /// <summary>
    /// 界面绑定。
    /// </summary>
    public static class UIFormBindings
    {
        public static readonly FairyGUIFormBinding[] Bindings = new FairyGUIFormBinding[]
        {
            new FairyGUIFormBinding((int)UIFormId.LoginAccountForm, GameMain.UI.Login.LoginAccountForm.URL, () => new GameMain.UI.Login.LoginAccountForm()),
            new FairyGUIFormBinding((int)UIFormId.LoginForm, GameMain.UI.Login.LoginForm.URL, () => new GameMain.UI.Login.LoginForm()),
        };
    }
}
