
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameMain.Demo
{ 
    /// <summary>
    /// Demo类型定义。
    /// </summary>
    public enum DemoType
    {
        /// <summary>
        /// 一
        /// </summary>
        First = 1,
        /// <summary>
        /// 二
        /// </summary>
        Second = 2,
    }

} 

