
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameMain.Demo
{
public sealed partial class DemoConfig : Luban.BeanBase
{
    public DemoConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Type = (Demo.DemoType)_buf.ReadInt();
        Name = _buf.ReadString();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);ParamList = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); ParamList.Add(_e0);}}
    }

    public static DemoConfig DeserializeDemoConfig(ByteBuf _buf)
    {
        return new Demo.DemoConfig(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 类型
    /// </summary>
    public readonly Demo.DemoType Type;
    /// <summary>
    /// 名字
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 参数列表
    /// </summary>
    public readonly System.Collections.Generic.List<int> ParamList;
   
    public const int __ID__ = -1517588496;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(GameMainDataTableSource tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "type:" + Type + ","
        + "name:" + Name + ","
        + "paramList:" + Luban.StringUtil.CollectionToString(ParamList) + ","
        + "}";
    }
}

}

