
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Cysharp.Threading.Tasks;
using HoweFramework;


namespace GameMain.Demo
{
public partial class TbDemoConfig : IDataTable
{
    private readonly string m_DataTableName;
    private readonly LoadDataTableFunc m_LoadDataTableFunc;
    private readonly LoadDataTableAsyncFunc m_LoadDataTableAsyncFunc;
    private readonly GameMainDataTableSource m_Manager;
    
    public static TbDemoConfig Instance { get; private set; }
    public DataTableLoadStatus LoadStatus { get; private set; }
    
    public TbDemoConfig(GameMainDataTableSource manager, string dataTableName, LoadDataTableFunc loadDataTableFunc, LoadDataTableAsyncFunc loadDataTableAsyncFunc)
    {
        Instance = this;
        m_Manager = manager;
        m_DataTableName = dataTableName;
        m_LoadDataTableFunc = loadDataTableFunc;
        m_LoadDataTableAsyncFunc = loadDataTableAsyncFunc;
        LoadStatus = DataTableLoadStatus.None;
    }

    public void Dispose()
    {
        Instance = null;
    }
    
    public void Load(bool autoResolveRef = true)
    {
        if (LoadStatus == DataTableLoadStatus.Loaded)
        {
            return;
        }
        
        if (LoadStatus == DataTableLoadStatus.Loading)
        {
            Log.Error("DataTable TbDemoConfig is loading");
            return;
        }
        
        LoadStatus = DataTableLoadStatus.Loading;
        var _buf = m_LoadDataTableFunc(m_DataTableName);
        if (_buf == null)
        {
            LoadStatus = DataTableLoadStatus.None;
            Log.Error("DataTable TbDemoConfig load failed");
            return;
        }
        
        LoadStatus = DataTableLoadStatus.Loaded;
        OnLoadSuccess(_buf);
        if (autoResolveRef)
        {
            ResolveRef();
        }
    }
    
    public async UniTask LoadAsync(bool autoResolveRef = true)
    {
        if (LoadStatus == DataTableLoadStatus.Loaded)
        {
            return;
        }
        
        if (LoadStatus == DataTableLoadStatus.Loading)
        {
            throw new System.Exception("DataTable TbDemoConfig is loading");
        }
        
        LoadStatus = DataTableLoadStatus.Loading;
        var _buf = await m_LoadDataTableAsyncFunc(m_DataTableName);
        if (_buf == null)
        {
            LoadStatus = DataTableLoadStatus.None;
            throw new System.Exception("DataTable TbDemoConfig load failed");
        }
        
        LoadStatus = DataTableLoadStatus.Loaded;
        OnLoadSuccess(_buf);
        if (autoResolveRef)
        {
            ResolveRef();
        }
    }

    private System.Collections.Generic.Dictionary<int, Demo.DemoConfig> _dataMap;
    private System.Collections.Generic.List<Demo.DemoConfig> _dataList;
    
    private void OnLoadSuccess(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Demo.DemoConfig>();
        _dataList = new System.Collections.Generic.List<Demo.DemoConfig>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            Demo.DemoConfig _v;
            _v = Demo.DemoConfig.DeserializeDemoConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Demo.DemoConfig> DataMap
    {
        get
        {
            Load();
            return _dataMap;
        }
    }
    
    public System.Collections.Generic.List<Demo.DemoConfig> DataList
    {
        get
        {
            Load();
            return _dataList;
        }
    }

    public Demo.DemoConfig GetOrDefault(int key) => DataMap.TryGetValue(key, out var v) ? v : null;
    public Demo.DemoConfig Get(int key) => DataMap[key];
    public Demo.DemoConfig this[int key] => DataMap[key];

    public void ResolveRef()
    {
        if (LoadStatus != DataTableLoadStatus.Loaded)
        {
            return;
        }
        
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(m_Manager);
        }
    }

}

}

