//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Threading;
using HoweFramework;

namespace GameMain.UI.Login
{
    public partial class LoginComp : FairyGUI.GComponent
    {
        public const string URL = "ui://6apezyp2hjkq1";

        #region [子节点]
 
        public FairyGUI.GButton ServerButton;
  
        public FairyGUI.GButton LoginButton;
 
        #endregion

        #region [控制器]

        #endregion

        #region [动效]

        #endregion
        
        public override void ConstructFromXML(FairyGUI.Utils.XML xml)
        {
            base.ConstructFromXML(xml);

            #region [子节点]
 
            ServerButton = (FairyGUI.GButton)GetChild("serverButton");
  
            LoginButton = (FairyGUI.GButton)GetChild("loginButton");
 
            #endregion

            #region [控制器]

            #endregion

            #region [动效]

            #endregion

            #region [生命周期事件]

            this.onAddedToStage.Add(_OnAddedToStage);
            this.onRemovedFromStage.Add(_OnRemoveFromStage);

            #endregion

            OnInitialize();
        }

        public override void Dispose()
        {
            OnDispose();
            
            base.Dispose();
        }
        
        #region [生命周期]
        
        private void _OnAddedToStage()
        {
            OnAddedToStage();
        }
        
        private void _OnRemoveFromStage()
        {
            OnRemoveFromStage();
        }
        
        #endregion
    }
}