//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameMain.UI.Login
{
    public partial class LoginAccountForm
    {
        public const string URL = "ui://eb0bof9pvq0qf";
        
        public override int FormId => (int)UIFormId.LoginAccountForm;

        #region [子节点]
   
        private FairyGUI.GTextInput m_InputAccount;
  
        private FairyGUI.GTextInput m_InputPassword;
  
        private FairyGUI.GButton m_BtnLogin;
  
        private FairyGUI.GButton m_BtnCancel;
 
        #endregion

        #region [控制器]

        #endregion

        #region [动效]

        #endregion
        
        private void RegisterComponents()
        {
            #region [子节点]
   
            m_InputAccount = (FairyGUI.GTextInput)ContentPane.GetChild("inputAccount");
  
            m_InputPassword = (FairyGUI.GTextInput)ContentPane.GetChild("inputPassword");
  
            m_BtnLogin = (FairyGUI.GButton)ContentPane.GetChild("btnLogin");
  
            m_BtnCancel = (FairyGUI.GButton)ContentPane.GetChild("btnCancel");
 
            #endregion

            #region [控制器]

            #endregion

            #region [动效]

            #endregion
        }

        protected override void OnInit()
        {
            RegisterComponents();
            OnInitialize();
        }

        public override void OnDestroy()
        {
            OnDispose();
            base.OnDestroy();
        }
    }
}