//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameMain.UI.login
{
    public partial class LoginForm
    {
        public const string URL = "ui://y2gydqzifycf0";
        
        public override int FormId => (int)UIFormId.LoginForm;

        #region [子节点]
  
        #endregion

        #region [控制器]

        #endregion

        #region [动效]

        #endregion
        
        private void RegisterComponents()
        {
            #region [子节点]
  
            #endregion

            #region [控制器]

            #endregion

            #region [动效]

            #endregion
        }

        protected override void OnInit()
        {
            RegisterComponents();
            OnInitialize();
        }

        public override void OnDestroy()
        {
            OnDispose();
            base.OnDestroy();
        }
    }
}