
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace DataTable.Game
{

    public sealed class ActionConfig : Luban.BeanBase
    {
        public ActionConfig(JToken _buf) 
        {
            JObject _obj = _buf as JObject;
            Id = (int)_obj.GetValue("id");
            Category = (Game.ActionCategoryType)(int)_obj.GetValue("category");
            { var __json0 = _obj.GetValue("param_list"); ParamList = new System.Collections.Generic.List<int>((__json0 as JArray).Count); foreach(JToken __e0 in __json0) { int __v0;  __v0 = (int)__e0;  ParamList.Add(__v0); }   }
            ParamStr = (string)_obj.GetValue("param_str");
        }

        public static ActionConfig DeserializeActionConfig(JToken _buf)
        {
            return new Game.ActionConfig(_buf);
        }

        /// <summary>
        /// id
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// 动作类型
        /// </summary>
        public readonly Game.ActionCategoryType Category;
        /// <summary>
        /// 参数列表
        /// </summary>
        public readonly System.Collections.Generic.List<int> ParamList;
        /// <summary>
        /// 参数字符串
        /// </summary>
        public readonly string ParamStr;


        public const int __ID__ = 1509087636;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef(DataTableList tables)
        {
        }

        public override string ToString()
        {
            return "{ "
            + "id:" + Id + ","
            + "category:" + Category + ","
            + "paramList:" + Luban.StringUtil.CollectionToString(ParamList) + ","
            + "paramStr:" + ParamStr + ","
            + "}";
        }
    }
}

