
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace DataTable.Game
{ 
    /// <summary>
    /// 动作类型定义。
    /// </summary>
    public enum ActionCategoryType
    {
        /// <summary>
        /// param_str=伤害表达式
        /// </summary>
        Damage = 1,
        /// <summary>
        /// param_list=buffId;层数
        /// </summary>
        AddBuff = 2,
    }

} 

