
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace DataTable.Game
{

    public sealed class BuffConfig : Luban.BeanBase
    {
        public BuffConfig(JToken _buf) 
        {
            JObject _obj = _buf as JObject;
            Id = (int)_obj.GetValue("id");
            Category = (Game.BuffCategoryType)(int)_obj.GetValue("category");
            Name = (string)_obj.GetValue("name");
            Duration = (int)_obj.GetValue("duration");
            StackLimit = (int)_obj.GetValue("stack_limit");
            { var __json0 = _obj.GetValue("param_list"); ParamList = new System.Collections.Generic.List<int>((__json0 as JArray).Count); foreach(JToken __e0 in __json0) { int __v0;  __v0 = (int)__e0;  ParamList.Add(__v0); }   }
        }

        public static BuffConfig DeserializeBuffConfig(JToken _buf)
        {
            return new Game.BuffConfig(_buf);
        }

        /// <summary>
        /// id
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// Buff类型
        /// </summary>
        public readonly Game.BuffCategoryType Category;
        /// <summary>
        /// 名字
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// 持续帧数
        /// </summary>
        public readonly int Duration;
        /// <summary>
        /// 层数上限(0代表无上限)
        /// </summary>
        public readonly int StackLimit;
        /// <summary>
        /// 参数列表
        /// </summary>
        public readonly System.Collections.Generic.List<int> ParamList;


        public const int __ID__ = -2027302671;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef(DataTableList tables)
        {
        }

        public override string ToString()
        {
            return "{ "
            + "id:" + Id + ","
            + "category:" + Category + ","
            + "name:" + Name + ","
            + "duration:" + Duration + ","
            + "stackLimit:" + StackLimit + ","
            + "paramList:" + Luban.StringUtil.CollectionToString(ParamList) + ","
            + "}";
        }
    }
}

