
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace DataTable.Game
{ 
    /// <summary>
    /// Buff类型定义。
    /// </summary>
    public enum BuffCategoryType
    {
        /// <summary>
        /// 伤害;间隔帧数
        /// </summary>
        FireBurn = 1,
    }

} 

