
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace DataTable.Game
{

    public sealed class SkillConfig : Luban.BeanBase
    {
        public SkillConfig(JToken _buf) 
        {
            JObject _obj = _buf as JObject;
            Id = (int)_obj.GetValue("id");
            Category = (Game.SkillCategoryType)(int)_obj.GetValue("category");
            Level = (int)_obj.GetValue("level");
            Name = (string)_obj.GetValue("name");
            PreCastDuration = (int)_obj.GetValue("pre_cast_duration");
            CastingDuration = (int)_obj.GetValue("casting_duration");
            PostCastDuration = (int)_obj.GetValue("post_cast_duration");
            CooldownDuration = (int)_obj.GetValue("cooldown_duration");
            { var __json0 = _obj.GetValue("param_list"); ParamList = new System.Collections.Generic.List<int>((__json0 as JArray).Count); foreach(JToken __e0 in __json0) { int __v0;  __v0 = (int)__e0;  ParamList.Add(__v0); }   }
            { var __json0 = _obj.GetValue("create_action_list"); CreateActionList = new System.Collections.Generic.List<int>((__json0 as JArray).Count); foreach(JToken __e0 in __json0) { int __v0;  __v0 = (int)__e0;  CreateActionList.Add(__v0); }   }
            { var __json0 = _obj.GetValue("ready_action_list"); ReadyActionList = new System.Collections.Generic.List<int>((__json0 as JArray).Count); foreach(JToken __e0 in __json0) { int __v0;  __v0 = (int)__e0;  ReadyActionList.Add(__v0); }   }
            { var __json0 = _obj.GetValue("pre_cast_action_list"); PreCastActionList = new System.Collections.Generic.List<int>((__json0 as JArray).Count); foreach(JToken __e0 in __json0) { int __v0;  __v0 = (int)__e0;  PreCastActionList.Add(__v0); }   }
            { var __json0 = _obj.GetValue("cast_action_list"); CastActionList = new System.Collections.Generic.List<int>((__json0 as JArray).Count); foreach(JToken __e0 in __json0) { int __v0;  __v0 = (int)__e0;  CastActionList.Add(__v0); }   }
            { var __json0 = _obj.GetValue("post_cast_action_list"); PostCastActionList = new System.Collections.Generic.List<int>((__json0 as JArray).Count); foreach(JToken __e0 in __json0) { int __v0;  __v0 = (int)__e0;  PostCastActionList.Add(__v0); }   }
        }

        public static SkillConfig DeserializeSkillConfig(JToken _buf)
        {
            return new Game.SkillConfig(_buf);
        }

        /// <summary>
        /// id
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// 技能类型
        /// </summary>
        public readonly Game.SkillCategoryType Category;
        /// <summary>
        /// 技能等级
        /// </summary>
        public readonly int Level;
        /// <summary>
        /// 名字
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// 前摇时间(逻辑帧数)
        /// </summary>
        public readonly int PreCastDuration;
        /// <summary>
        /// 施法时间(逻辑帧数)
        /// </summary>
        public readonly int CastingDuration;
        /// <summary>
        /// 后摇时间(逻辑帧数)
        /// </summary>
        public readonly int PostCastDuration;
        /// <summary>
        /// 冷却时间(逻辑帧数)
        /// </summary>
        public readonly int CooldownDuration;
        /// <summary>
        /// 参数列表
        /// </summary>
        public readonly System.Collections.Generic.List<int> ParamList;
        /// <summary>
        /// 技能创建行动列表
        /// </summary>
        public readonly System.Collections.Generic.List<int> CreateActionList;
        /// <summary>
        /// 技能就绪行动列表
        /// </summary>
        public readonly System.Collections.Generic.List<int> ReadyActionList;
        /// <summary>
        /// 技能前摇行动列表
        /// </summary>
        public readonly System.Collections.Generic.List<int> PreCastActionList;
        /// <summary>
        /// 技能施法行动列表
        /// </summary>
        public readonly System.Collections.Generic.List<int> CastActionList;
        /// <summary>
        /// 技能后摇行动列表
        /// </summary>
        public readonly System.Collections.Generic.List<int> PostCastActionList;


        public const int __ID__ = 273812727;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef(DataTableList tables)
        {
        }

        public override string ToString()
        {
            return "{ "
            + "id:" + Id + ","
            + "category:" + Category + ","
            + "level:" + Level + ","
            + "name:" + Name + ","
            + "preCastDuration:" + PreCastDuration + ","
            + "castingDuration:" + CastingDuration + ","
            + "postCastDuration:" + PostCastDuration + ","
            + "cooldownDuration:" + CooldownDuration + ","
            + "paramList:" + Luban.StringUtil.CollectionToString(ParamList) + ","
            + "createActionList:" + Luban.StringUtil.CollectionToString(CreateActionList) + ","
            + "readyActionList:" + Luban.StringUtil.CollectionToString(ReadyActionList) + ","
            + "preCastActionList:" + Luban.StringUtil.CollectionToString(PreCastActionList) + ","
            + "castActionList:" + Luban.StringUtil.CollectionToString(CastActionList) + ","
            + "postCastActionList:" + Luban.StringUtil.CollectionToString(PostCastActionList) + ","
            + "}";
        }
    }
}

