
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace DataTable.Game
{

    public class TbBuffConfig : IDataTable
    {
        private readonly System.Collections.Generic.Dictionary<int, Game.BuffConfig> _dataMap;
        private readonly System.Collections.Generic.List<Game.BuffConfig> _dataList;
        
        public TbBuffConfig(JArray _buf)
        {
            _dataMap = new System.Collections.Generic.Dictionary<int, Game.BuffConfig>();
            _dataList = new System.Collections.Generic.List<Game.BuffConfig>();
            
            foreach(JObject _ele in _buf)
            {
                Game.BuffConfig _v;
                _v = Game.BuffConfig.DeserializeBuffConfig(_ele);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }
        }


        public System.Collections.Generic.Dictionary<int, Game.BuffConfig> DataMap => _dataMap;
        public System.Collections.Generic.List<Game.BuffConfig> DataList => _dataList;

        public Game.BuffConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
        public Game.BuffConfig Get(int key) => _dataMap[key];
        public Game.BuffConfig this[int key] => _dataMap[key];

        public void ResolveRef(DataTableList tables)
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef(tables);
            }
        }

    }
}

