// <auto-generated>
// THIS (.cs) FILE IS GENERATED BY MPC(MessagePack-CSharp). DO NOT CHANGE IT.
// </auto-generated>

#pragma warning disable 618
#pragma warning disable 612
#pragma warning disable 414
#pragma warning disable 168
#pragma warning disable CS1591 // document public APIs

#pragma warning disable SA1312 // Variable names should begin with lower-case letter
#pragma warning disable SA1649 // File name should match first type name

namespace MessagePack.Resolvers
{
    public class GeneratedResolver : global::MessagePack.IFormatterResolver
    {
        public static readonly global::MessagePack.IFormatterResolver Instance = new GeneratedResolver();

        private GeneratedResolver()
        {
        }

        public global::MessagePack.Formatters.IMessagePackFormatter<T> GetFormatter<T>()
        {
            return FormatterCache<T>.Formatter;
        }

        private static class FormatterCache<T>
        {
            internal static readonly global::MessagePack.Formatters.IMessagePackFormatter<T> Formatter;

            static FormatterCache()
            {
                var f = GeneratedResolverGetFormatterHelper.GetFormatter(typeof(T));
                if (f != null)
                {
                    Formatter = (global::MessagePack.Formatters.IMessagePackFormatter<T>)f;
                }
            }
        }
    }

    internal static class GeneratedResolverGetFormatterHelper
    {
        private static readonly global::System.Collections.Generic.Dictionary<global::System.Type, int> lookup;

        static GeneratedResolverGetFormatterHelper()
        {
            lookup = new global::System.Collections.Generic.Dictionary<global::System.Type, int>(19)
            {
                { typeof(global::System.Collections.Generic.Dictionary<int, long>), 0 },
                { typeof(global::Geek.Server.Proto.KickOutReason), 1 },
                { typeof(global::Geek.Server.Proto.Proto.TestEnum), 2 },
                { typeof(global::ClientProto.HearBeat), 3 },
                { typeof(global::ClientProto.NetConnectMessage), 4 },
                { typeof(global::ClientProto.NetDisConnectMessage), 5 },
                { typeof(global::Geek.Server.Proto.BagComposePetReq), 6 },
                { typeof(global::Geek.Server.Proto.BagComposePetResp), 7 },
                { typeof(global::Geek.Server.Proto.BagSellItemReq), 8 },
                { typeof(global::Geek.Server.Proto.BagUseItemReq), 9 },
                { typeof(global::Geek.Server.Proto.CommonResp), 10 },
                { typeof(global::Geek.Server.Proto.KickOut), 11 },
                { typeof(global::Geek.Server.Proto.LoginReq), 12 },
                { typeof(global::Geek.Server.Proto.LoginResp), 13 },
                { typeof(global::Geek.Server.Proto.Proto.A), 14 },
                { typeof(global::Geek.Server.Proto.Proto.B), 15 },
                { typeof(global::Geek.Server.Proto.Proto.TestStruct), 16 },
                { typeof(global::Geek.Server.Proto.UserBagInfo), 17 },
                { typeof(global::Geek.Server.Proto.UserInfo), 18 },
            };
        }

        internal static object GetFormatter(global::System.Type t)
        {
            int key;
            if (!lookup.TryGetValue(t, out key))
            {
                return null;
            }

            switch (key)
            {
                case 0: return new global::MessagePack.Formatters.DictionaryFormatter<int, long>();
                case 1: return new MessagePack.Formatters.Geek.Server.Proto.KickOutReasonFormatter();
                case 2: return new MessagePack.Formatters.Geek.Server.Proto.Proto.TestEnumFormatter();
                case 3: return new MessagePack.Formatters.ClientProto.HearBeatFormatter();
                case 4: return new MessagePack.Formatters.ClientProto.NetConnectMessageFormatter();
                case 5: return new MessagePack.Formatters.ClientProto.NetDisConnectMessageFormatter();
                case 6: return new MessagePack.Formatters.Geek.Server.Proto.BagComposePetReqFormatter();
                case 7: return new MessagePack.Formatters.Geek.Server.Proto.BagComposePetRespFormatter();
                case 8: return new MessagePack.Formatters.Geek.Server.Proto.BagSellItemReqFormatter();
                case 9: return new MessagePack.Formatters.Geek.Server.Proto.BagUseItemReqFormatter();
                case 10: return new MessagePack.Formatters.Geek.Server.Proto.CommonRespFormatter();
                case 11: return new MessagePack.Formatters.Geek.Server.Proto.KickOutFormatter();
                case 12: return new MessagePack.Formatters.Geek.Server.Proto.LoginReqFormatter();
                case 13: return new MessagePack.Formatters.Geek.Server.Proto.LoginRespFormatter();
                case 14: return new MessagePack.Formatters.Geek.Server.Proto.Proto.AFormatter();
                case 15: return new MessagePack.Formatters.Geek.Server.Proto.Proto.BFormatter();
                case 16: return new MessagePack.Formatters.Geek.Server.Proto.Proto.TestStructFormatter();
                case 17: return new MessagePack.Formatters.Geek.Server.Proto.UserBagInfoFormatter();
                case 18: return new MessagePack.Formatters.Geek.Server.Proto.UserInfoFormatter();
                default: return null;
            }
        }
    }
}

#pragma warning restore 168
#pragma warning restore 414
#pragma warning restore 618
#pragma warning restore 612

#pragma warning restore SA1312 // Variable names should begin with lower-case letter
#pragma warning restore SA1649 // File name should match first type name
