//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameMain.UI.Loading
{
    public partial class LoadingForm
    {
        public const string URL = "ui://3vxqn7cjnby30";
        
        public override int FormId => (int)UIFormId.LoadingForm;

        #region [子节点]
   
        private FairyGUI.GProgressBar m_Progress;
 
        #endregion

        #region [控制器]

        #endregion

        #region [动效]

        #endregion
        
        private void RegisterComponents()
        {
            #region [子节点]
   
            m_Progress = (FairyGUI.GProgressBar)ContentPane.GetChild("progress");
 
            #endregion

            #region [控制器]

            #endregion

            #region [动效]

            #endregion
        }

        protected override void OnInit()
        {
            RegisterComponents();
            OnInitialize();
        }

        public override void OnDestroy()
        {
            OnDispose();
            base.OnDestroy();
        }
    }
}