
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameMain.Game
{
public sealed partial class ActionConfig : Luban.BeanBase
{
    public ActionConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Category = (Game.ActionCategoryType)_buf.ReadInt();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);ParamList = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); ParamList.Add(_e0);}}
        ParamStr = _buf.ReadString();
    }

    public static ActionConfig DeserializeActionConfig(ByteBuf _buf)
    {
        return new Game.ActionConfig(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 动作类型
    /// </summary>
    public readonly Game.ActionCategoryType Category;
    /// <summary>
    /// 参数列表
    /// </summary>
    public readonly System.Collections.Generic.List<int> ParamList;
    /// <summary>
    /// 参数字符串
    /// </summary>
    public readonly string ParamStr;
   
    public const int __ID__ = 1509087636;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(GameMainDataTableSource tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "category:" + Category + ","
        + "paramList:" + Luban.StringUtil.CollectionToString(ParamList) + ","
        + "paramStr:" + ParamStr + ","
        + "}";
    }
}

}

