
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameMain.Game
{
public sealed partial class BuffConfig : Luban.BeanBase
{
    public BuffConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Category = (Game.BuffCategoryType)_buf.ReadInt();
        Name = _buf.ReadString();
        Desc = _buf.ReadString();
        Duration = _buf.ReadInt();
        StackLimit = _buf.ReadInt();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);ParamList = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); ParamList.Add(_e0);}}
    }

    public static BuffConfig DeserializeBuffConfig(ByteBuf _buf)
    {
        return new Game.BuffConfig(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// Buff类型
    /// </summary>
    public readonly Game.BuffCategoryType Category;
    /// <summary>
    /// 名字
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 持续帧数
    /// </summary>
    public readonly int Duration;
    /// <summary>
    /// 层数上限(0代表无上限)
    /// </summary>
    public readonly int StackLimit;
    /// <summary>
    /// 参数列表
    /// </summary>
    public readonly System.Collections.Generic.List<int> ParamList;
   
    public const int __ID__ = -2027302671;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(GameMainDataTableSource tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "category:" + Category + ","
        + "name:" + Name + ","
        + "desc:" + Desc + ","
        + "duration:" + Duration + ","
        + "stackLimit:" + StackLimit + ","
        + "paramList:" + Luban.StringUtil.CollectionToString(ParamList) + ","
        + "}";
    }
}

}

