
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameMain.Game
{ 
    /// <summary>
    /// 技能类型定义。
    /// </summary>
    public enum SkillCategoryType
    {
        /// <summary>
        /// 火球
        /// </summary>
        FireBall = 1,
    }

} 

