
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameMain.Game
{
public sealed partial class SkillConfig : Luban.BeanBase
{
    public SkillConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Category = (Game.SkillCategoryType)_buf.ReadInt();
        Level = _buf.ReadInt();
        Name = _buf.ReadString();
        Desc = _buf.ReadString();
        PreCastDuration = _buf.ReadInt();
        CastingDuration = _buf.ReadInt();
        PostCastDuration = _buf.ReadInt();
        CooldownDuration = _buf.ReadInt();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);ParamList = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); ParamList.Add(_e0);}}
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);CreateActionList = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); CreateActionList.Add(_e0);}}
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);ReadyActionList = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); ReadyActionList.Add(_e0);}}
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);PreCastActionList = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); PreCastActionList.Add(_e0);}}
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);CastActionList = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); CastActionList.Add(_e0);}}
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);PostCastActionList = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); PostCastActionList.Add(_e0);}}
    }

    public static SkillConfig DeserializeSkillConfig(ByteBuf _buf)
    {
        return new Game.SkillConfig(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 技能类型
    /// </summary>
    public readonly Game.SkillCategoryType Category;
    /// <summary>
    /// 技能等级
    /// </summary>
    public readonly int Level;
    /// <summary>
    /// 名字
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 前摇时间(逻辑帧数)
    /// </summary>
    public readonly int PreCastDuration;
    /// <summary>
    /// 施法时间(逻辑帧数)
    /// </summary>
    public readonly int CastingDuration;
    /// <summary>
    /// 后摇时间(逻辑帧数)
    /// </summary>
    public readonly int PostCastDuration;
    /// <summary>
    /// 冷却时间(逻辑帧数)
    /// </summary>
    public readonly int CooldownDuration;
    /// <summary>
    /// 参数列表
    /// </summary>
    public readonly System.Collections.Generic.List<int> ParamList;
    /// <summary>
    /// 技能创建行动列表
    /// </summary>
    public readonly System.Collections.Generic.List<int> CreateActionList;
    /// <summary>
    /// 技能就绪行动列表
    /// </summary>
    public readonly System.Collections.Generic.List<int> ReadyActionList;
    /// <summary>
    /// 技能前摇行动列表
    /// </summary>
    public readonly System.Collections.Generic.List<int> PreCastActionList;
    /// <summary>
    /// 技能施法行动列表
    /// </summary>
    public readonly System.Collections.Generic.List<int> CastActionList;
    /// <summary>
    /// 技能后摇行动列表
    /// </summary>
    public readonly System.Collections.Generic.List<int> PostCastActionList;
   
    public const int __ID__ = 273812727;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(GameMainDataTableSource tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "category:" + Category + ","
        + "level:" + Level + ","
        + "name:" + Name + ","
        + "desc:" + Desc + ","
        + "preCastDuration:" + PreCastDuration + ","
        + "castingDuration:" + CastingDuration + ","
        + "postCastDuration:" + PostCastDuration + ","
        + "cooldownDuration:" + CooldownDuration + ","
        + "paramList:" + Luban.StringUtil.CollectionToString(ParamList) + ","
        + "createActionList:" + Luban.StringUtil.CollectionToString(CreateActionList) + ","
        + "readyActionList:" + Luban.StringUtil.CollectionToString(ReadyActionList) + ","
        + "preCastActionList:" + Luban.StringUtil.CollectionToString(PreCastActionList) + ","
        + "castActionList:" + Luban.StringUtil.CollectionToString(CastActionList) + ","
        + "postCastActionList:" + Luban.StringUtil.CollectionToString(PostCastActionList) + ","
        + "}";
    }
}

}

